<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Omar Khattab">

<title>Football Player Stats</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="FUTBOLFINAL_files/libs/clipboard/clipboard.min.js"></script>
<script src="FUTBOLFINAL_files/libs/quarto-html/quarto.js"></script>
<script src="FUTBOLFINAL_files/libs/quarto-html/popper.min.js"></script>
<script src="FUTBOLFINAL_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="FUTBOLFINAL_files/libs/quarto-html/anchor.min.js"></script>
<link href="FUTBOLFINAL_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="FUTBOLFINAL_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="FUTBOLFINAL_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="FUTBOLFINAL_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="FUTBOLFINAL_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Football Player Stats</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Omar Khattab </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>For this project, I used the <strong>2022–2023 Football Player Stats</strong> dataset. The dataset includes performance statistics for football players across European club teams.</p>
<p>The 3 questions:</p>
<ol type="1">
<li>Do Brazilian players score more goals or italian players.</li>
</ol>
<p>^^Do South American players score significantly more goals than European players? ^^(This will be done by grouping players into 2 (Europeans) and (South Americans)</p>
<ol start="2" type="1">
<li><p>Is there a relationship between minutes played and goals scored?</p></li>
<li><p>Do more completed passed into the 18 yard box result in more assists?</p></li>
</ol>
</section>
<section id="data-description" class="level1">
<h1>Data Description</h1>
<p>Here are the key variables:</p>
<ul>
<li><code>Name</code>: Player’s name<br>
</li>
<li><code>Nation</code>: Country of the player<br>
</li>
<li><code>Goals</code>: Number of goals scored<br>
</li>
<li><code>MinutesPlayed</code>: Total minutes played<br>
</li>
<li><code>Position</code>: Playing position (e.g., FW, MF, DF)<br>
</li>
<li><code>Age</code>: Player’s age</li>
<li><code>PPA</code> : Completed passes into the 18-yard box</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>players <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(<span class="st">"2022-2023-Football-Player-Stats.csv"</span>, <span class="at">delim =</span> <span class="st">";"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 2689 Columns: 124
── Column specification ────────────────────────────────────────────────────────
Delimiter: ";"
chr   (5): Player, Nation, Pos, Squad, Comp
dbl (119): Rk, Age, Born, MP, Starts, Min, 90s, Goals, Shots, SoT, SoT%, G/S...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(players)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 2,689
Columns: 124
$ Rk            &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 1…
$ Player        &lt;chr&gt; "Brenden Aaronson", "Yunis Abdelhamid", "Himad Abdelli",…
$ Nation        &lt;chr&gt; "USA", "MAR", "FRA", "GHA", "FRA", "DEN", "FRA", "FRA", …
$ Pos           &lt;chr&gt; "MFFW", "DF", "MFFW", "MF", "MF", "MF", "FWMF", "FWMF", …
$ Squad         &lt;chr&gt; "Leeds United", "Reims", "Angers", "Lens", "Lorient", "H…
$ Comp          &lt;chr&gt; "Premier League", "Ligue 1", "Ligue 1", "Ligue 1", "Ligu…
$ Age           &lt;dbl&gt; 22, 35, 23, 22, 30, 26, 19, 19, 22, 22, 25, 35, 21, 31, …
$ Born          &lt;dbl&gt; 2000, 1987, 1999, 2000, 1993, 1996, 2003, 2003, 2000, 20…
$ MP            &lt;dbl&gt; 20, 22, 14, 20, 15, 1, 5, 11, 4, 22, 22, 14, 2, 16, 21, …
$ Starts        &lt;dbl&gt; 19, 22, 8, 20, 15, 0, 2, 0, 3, 17, 18, 12, 0, 12, 18, 19…
$ Min           &lt;dbl&gt; 1596, 1980, 770, 1799, 1165, 11, 185, 107, 272, 1507, 15…
$ `90s`         &lt;dbl&gt; 17.7, 22.0, 8.6, 20.0, 12.9, 0.1, 2.1, 1.2, 3.0, 16.7, 1…
$ Goals         &lt;dbl&gt; 1, 0, 0, 1, 0, 0, 1, 1, 0, 5, 6, 0, 0, 2, 4, 0, 1, 1, 0,…
$ Shots         &lt;dbl&gt; 1.53, 0.86, 1.05, 0.60, 0.31, 0.00, 4.29, 5.00, 0.67, 2.…
$ SoT           &lt;dbl&gt; 0.28, 0.05, 0.35, 0.15, 0.00, 0.00, 1.43, 1.67, 0.33, 1.…
$ `SoT%`        &lt;dbl&gt; 18.5, 5.3, 33.3, 25.0, 0.0, 0.0, 33.3, 33.3, 50.0, 37.0,…
$ `G/Sh`        &lt;dbl&gt; 0.04, 0.00, 0.00, 0.08, 0.00, 0.00, 0.11, 0.17, 0.00, 0.…
$ `G/SoT`       &lt;dbl&gt; 0.20, 0.00, 0.00, 0.33, 0.00, 0.00, 0.33, 0.50, 0.00, 0.…
$ ShoDist       &lt;dbl&gt; 19.0, 13.5, 19.2, 20.3, 23.9, 0.0, 20.4, 12.2, 7.8, 18.1…
$ ShoFK         &lt;dbl&gt; 0.11, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.…
$ ShoPK         &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ PKatt         &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ PasTotCmp     &lt;dbl&gt; 23.20, 38.50, 40.00, 59.50, 37.90, 20.00, 7.14, 5.83, 39…
$ PasTotAtt     &lt;dbl&gt; 31.0, 47.2, 49.5, 64.9, 43.4, 30.0, 10.0, 12.5, 54.3, 25…
$ `PasTotCmp%`  &lt;dbl&gt; 74.9, 81.5, 80.8, 91.6, 87.3, 66.7, 71.4, 46.7, 71.8, 69…
$ PasTotDist    &lt;dbl&gt; 293.0, 751.5, 676.0, 946.3, 613.6, 310.0, 139.5, 107.5, …
$ PasTotPrgDist &lt;dbl&gt; 85.7, 318.5, 188.1, 226.9, 224.7, 90.0, 40.0, 25.0, 265.…
$ PasShoCmp     &lt;dbl&gt; 13.30, 10.90, 18.50, 29.60, 17.90, 10.00, 1.43, 2.50, 20…
$ PasShoAtt     &lt;dbl&gt; 16.20, 12.90, 22.00, 31.80, 19.40, 10.00, 2.38, 5.00, 23…
$ `PasShoCmp%`  &lt;dbl&gt; 81.9, 84.5, 84.1, 93.2, 92.4, 100.0, 60.0, 50.0, 88.6, 7…
$ PasMedCmp     &lt;dbl&gt; 5.93, 23.20, 15.50, 24.70, 15.70, 10.00, 4.76, 2.50, 13.…
$ PasMedAtt     &lt;dbl&gt; 7.74, 25.70, 18.70, 26.20, 17.80, 10.00, 5.24, 3.33, 20.…
$ `PasMedCmp%`  &lt;dbl&gt; 76.6, 90.1, 82.6, 94.3, 88.6, 100.0, 90.9, 75.0, 66.7, 7…
$ PasLonCmp     &lt;dbl&gt; 0.90, 3.77, 4.42, 3.35, 2.64, 0.00, 0.48, 0.83, 2.33, 0.…
$ PasLonAtt     &lt;dbl&gt; 2.37, 7.00, 5.93, 4.30, 3.95, 10.00, 0.95, 0.83, 5.67, 0…
$ `PasLonCmp%`  &lt;dbl&gt; 38.1, 53.9, 74.5, 77.9, 66.7, 0.0, 50.0, 100.0, 41.2, 28…
$ Assists       &lt;dbl&gt; 0.11, 0.05, 0.00, 0.00, 0.08, 0.00, 0.00, 0.00, 0.00, 0.…
$ PasAss        &lt;dbl&gt; 1.75, 0.27, 1.51, 0.50, 0.62, 0.00, 0.00, 1.67, 0.00, 0.…
$ Pas3rd        &lt;dbl&gt; 1.75, 2.91, 3.95, 6.00, 3.88, 0.00, 0.48, 0.83, 3.00, 0.…
$ PPA           &lt;dbl&gt; 0.45, 0.09, 1.74, 0.55, 0.39, 0.00, 1.43, 0.83, 0.33, 0.…
$ CrsPA         &lt;dbl&gt; 0.11, 0.00, 0.35, 0.10, 0.00, 0.00, 0.48, 0.00, 0.00, 0.…
$ PasProg       &lt;dbl&gt; 3.22, 4.50, 6.40, 5.60, 5.04, 0.00, 1.90, 1.67, 3.33, 1.…
$ PasAtt        &lt;dbl&gt; 31.0, 47.2, 49.5, 64.9, 43.4, 30.0, 10.0, 12.5, 54.3, 25…
$ PasLive       &lt;dbl&gt; 28.10, 43.30, 48.10, 63.10, 42.60, 30.00, 9.05, 12.50, 4…
$ PasDead       &lt;dbl&gt; 2.88, 3.73, 1.16, 1.40, 0.78, 0.00, 0.95, 0.00, 11.70, 0…
$ PasFK         &lt;dbl&gt; 0.96, 3.32, 0.35, 1.30, 0.78, 0.00, 0.00, 0.00, 0.33, 0.…
$ TB            &lt;dbl&gt; 0.17, 0.00, 0.12, 0.05, 0.39, 0.00, 0.00, 0.83, 0.00, 0.…
$ Sw            &lt;dbl&gt; 0.00, 0.55, 0.23, 0.20, 0.16, 0.00, 0.00, 0.00, 0.67, 0.…
$ PasCrs        &lt;dbl&gt; 2.54, 0.18, 1.05, 0.35, 0.23, 0.00, 0.95, 1.67, 1.33, 0.…
$ TI            &lt;dbl&gt; 0.23, 0.09, 0.81, 0.10, 0.00, 0.00, 0.00, 0.00, 11.30, 0…
$ CK            &lt;dbl&gt; 1.47, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.…
$ CkIn          &lt;dbl&gt; 0.68, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.…
$ CkOut         &lt;dbl&gt; 0.62, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.…
$ CkStr         &lt;dbl&gt; 0.06, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.…
$ PasCmp        &lt;dbl&gt; 23.20, 38.50, 40.00, 59.50, 37.90, 20.00, 7.14, 5.83, 39…
$ PasOff        &lt;dbl&gt; 0.00, 0.23, 0.23, 0.35, 0.08, 0.00, 0.00, 0.00, 0.33, 0.…
$ PasBlocks     &lt;dbl&gt; 0.85, 0.59, 1.16, 0.40, 0.31, 0.00, 0.48, 0.83, 2.33, 1.…
$ SCA           &lt;dbl&gt; 3.62, 1.14, 2.67, 1.60, 1.24, 0.00, 0.48, 5.83, 1.00, 2.…
$ ScaPassLive   &lt;dbl&gt; 2.37, 0.86, 2.44, 1.35, 1.01, 0.00, 0.48, 1.67, 0.67, 1.…
$ ScaPassDead   &lt;dbl&gt; 0.56, 0.00, 0.00, 0.00, 0.08, 0.00, 0.00, 0.00, 0.00, 0.…
$ ScaDrib       &lt;dbl&gt; 0.23, 0.00, 0.00, 0.10, 0.00, 0.00, 0.00, 0.00, 0.33, 0.…
$ ScaSh         &lt;dbl&gt; 0.11, 0.18, 0.12, 0.10, 0.08, 0.00, 0.00, 2.50, 0.00, 0.…
$ ScaFld        &lt;dbl&gt; 0.28, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.83, 0.00, 0.…
$ ScaDef        &lt;dbl&gt; 0.06, 0.09, 0.12, 0.05, 0.08, 0.00, 0.00, 0.83, 0.00, 0.…
$ GCA           &lt;dbl&gt; 0.28, 0.18, 0.00, 0.00, 0.08, 0.00, 0.00, 1.67, 0.33, 0.…
$ GcaPassLive   &lt;dbl&gt; 0.17, 0.14, 0.00, 0.00, 0.08, 0.00, 0.00, 0.00, 0.33, 0.…
$ GcaPassDead   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ GcaDrib       &lt;dbl&gt; 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.…
$ GcaSh         &lt;dbl&gt; 0.06, 0.05, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.…
$ GcaFld        &lt;dbl&gt; 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.83, 0.00, 0.…
$ GcaDef        &lt;dbl&gt; 0.06, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.83, 0.00, 0.…
$ Tkl           &lt;dbl&gt; 1.64, 2.50, 2.91, 1.50, 3.80, 10.00, 1.43, 0.83, 2.67, 1…
$ TklWon        &lt;dbl&gt; 0.51, 1.59, 1.40, 0.80, 2.02, 10.00, 0.48, 0.83, 2.33, 0…
$ TklDef3rd     &lt;dbl&gt; 0.45, 1.45, 1.28, 0.55, 2.64, 0.00, 0.00, 0.00, 2.33, 0.…
$ TklMid3rd     &lt;dbl&gt; 0.90, 1.00, 1.40, 0.85, 1.16, 0.00, 0.95, 0.00, 0.33, 0.…
$ TklAtt3rd     &lt;dbl&gt; 0.28, 0.05, 0.23, 0.10, 0.00, 10.00, 0.48, 0.83, 0.00, 0…
$ TklDri        &lt;dbl&gt; 0.51, 1.32, 1.63, 0.85, 1.32, 0.00, 0.00, 0.83, 2.00, 0.…
$ TklDriAtt     &lt;dbl&gt; 1.47, 1.68, 2.67, 1.30, 3.26, 0.00, 0.95, 0.83, 2.33, 1.…
$ `TklDri%`     &lt;dbl&gt; 34.6, 78.4, 60.9, 65.4, 40.5, 0.0, 0.0, 100.0, 85.7, 22.…
$ TklDriPast    &lt;dbl&gt; 0.96, 0.36, 1.05, 0.45, 1.94, 0.00, 0.95, 0.00, 0.33, 1.…
$ Blocks        &lt;dbl&gt; 1.69, 2.23, 1.51, 1.30, 1.40, 0.00, 0.48, 0.83, 1.33, 0.…
$ BlkSh         &lt;dbl&gt; 0.11, 0.77, 0.12, 0.35, 0.23, 0.00, 0.00, 0.00, 0.67, 0.…
$ BlkPass       &lt;dbl&gt; 1.58, 1.45, 1.40, 0.95, 1.16, 0.00, 0.48, 0.83, 0.67, 0.…
$ Int           &lt;dbl&gt; 0.06, 2.00, 0.93, 1.10, 1.16, 0.00, 0.48, 1.67, 2.00, 0.…
$ `Tkl+Int`     &lt;dbl&gt; 1.69, 4.50, 3.84, 2.60, 4.96, 10.00, 1.90, 2.50, 4.67, 1…
$ Clr           &lt;dbl&gt; 0.28, 2.91, 0.93, 0.80, 1.55, 0.00, 0.48, 0.83, 2.67, 0.…
$ Err           &lt;dbl&gt; 0.06, 0.05, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.…
$ Touches       &lt;dbl&gt; 44.0, 59.2, 62.6, 73.3, 54.7, 50.0, 25.7, 30.8, 65.7, 38…
$ TouDefPen     &lt;dbl&gt; 0.40, 6.23, 0.93, 2.10, 3.26, 0.00, 0.48, 0.83, 4.67, 0.…
$ TouDef3rd     &lt;dbl&gt; 4.35, 27.50, 11.40, 12.00, 19.20, 20.00, 1.43, 0.83, 20.…
$ TouMid3rd     &lt;dbl&gt; 19.0, 29.5, 36.0, 49.6, 31.4, 20.0, 11.4, 12.5, 30.7, 14…
$ TouAtt3rd     &lt;dbl&gt; 21.50, 2.73, 17.40, 12.20, 4.88, 10.00, 12.90, 18.30, 15…
$ TouAttPen     &lt;dbl&gt; 2.49, 1.09, 1.16, 0.70, 0.23, 0.00, 6.67, 12.50, 1.67, 4…
$ TouLive       &lt;dbl&gt; 44.0, 59.2, 62.6, 73.3, 54.7, 50.0, 25.7, 30.8, 65.7, 38…
$ ToAtt         &lt;dbl&gt; 3.73, 0.68, 3.84, 1.25, 0.93, 0.00, 1.43, 0.00, 1.33, 3.…
$ ToSuc         &lt;dbl&gt; 1.19, 0.32, 2.09, 0.70, 0.54, 0.00, 0.48, 0.00, 0.33, 1.…
$ `ToSuc%`      &lt;dbl&gt; 31.8, 46.7, 54.5, 56.0, 58.3, 0.0, 33.3, 0.0, 25.0, 32.1…
$ ToTkl         &lt;dbl&gt; 1.75, 0.36, 1.51, 0.40, 0.31, 0.00, 0.95, 0.00, 1.00, 1.…
$ `ToTkl%`      &lt;dbl&gt; 47.0, 53.3, 39.4, 32.0, 33.3, 0.0, 66.7, 0.0, 75.0, 58.5…
$ Carries       &lt;dbl&gt; 26.7, 40.0, 48.5, 61.0, 41.0, 10.0, 17.1, 22.5, 30.3, 28…
$ CarTotDist    &lt;dbl&gt; 136.1, 234.2, 298.5, 316.9, 174.3, 0.0, 97.1, 145.0, 112…
$ CarPrgDist    &lt;dbl&gt; 56.6, 125.0, 151.0, 117.5, 72.7, 0.0, 10.5, 87.5, 67.3, …
$ CarProg       &lt;dbl&gt; 1.53, 0.55, 2.56, 1.25, 0.47, 0.00, 1.43, 3.33, 0.67, 3.…
$ Car3rd        &lt;dbl&gt; 1.07, 0.23, 2.56, 1.95, 0.93, 0.00, 0.00, 0.83, 0.67, 1.…
$ CPA           &lt;dbl&gt; 0.40, 0.09, 0.47, 0.15, 0.00, 0.00, 0.95, 1.67, 0.33, 1.…
$ CarMis        &lt;dbl&gt; 2.60, 0.73, 2.09, 1.35, 1.32, 0.00, 7.62, 8.33, 1.00, 2.…
$ CarDis        &lt;dbl&gt; 3.11, 0.68, 1.05, 1.30, 0.78, 0.00, 3.33, 0.83, 0.67, 0.…
$ Rec           &lt;dbl&gt; 30.2, 34.5, 43.4, 56.5, 36.4, 10.0, 19.0, 22.5, 35.0, 27…
$ RecProg       &lt;dbl&gt; 5.65, 0.23, 5.93, 1.70, 0.47, 0.00, 6.67, 9.17, 3.67, 9.…
$ CrdY          &lt;dbl&gt; 0.11, 0.09, 0.12, 0.15, 0.16, 0.00, 0.00, 0.00, 0.00, 0.…
$ CrdR          &lt;dbl&gt; 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.…
$ `2CrdY`       &lt;dbl&gt; 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.…
$ Fls           &lt;dbl&gt; 0.62, 1.32, 1.74, 2.45, 0.93, 0.00, 0.95, 2.50, 0.67, 1.…
$ Fld           &lt;dbl&gt; 2.26, 0.50, 1.28, 1.35, 1.01, 0.00, 1.43, 4.17, 0.67, 1.…
$ Off           &lt;dbl&gt; 0.17, 0.05, 0.00, 0.00, 0.00, 0.00, 0.48, 0.83, 0.00, 0.…
$ Crs           &lt;dbl&gt; 2.54, 0.18, 1.05, 0.35, 0.23, 0.00, 0.95, 1.67, 1.33, 0.…
$ TklW          &lt;dbl&gt; 0.51, 1.59, 1.40, 0.80, 2.02, 10.00, 0.48, 0.83, 2.33, 0…
$ PKwon         &lt;dbl&gt; 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.83, 0.00, 0.…
$ PKcon         &lt;dbl&gt; 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.…
$ OG            &lt;dbl&gt; 0.00, 0.00, 0.00, 0.05, 0.00, 0.00, 0.00, 0.00, 0.00, 0.…
$ Recov         &lt;dbl&gt; 4.86, 6.64, 8.14, 6.60, 6.51, 10.00, 0.48, 1.67, 6.00, 4…
$ AerWon        &lt;dbl&gt; 0.34, 2.18, 0.93, 0.50, 0.31, 0.00, 1.43, 0.83, 1.00, 0.…
$ AerLost       &lt;dbl&gt; 1.19, 1.23, 1.05, 0.50, 0.39, 10.00, 1.43, 3.33, 2.00, 1…
$ `AerWon%`     &lt;dbl&gt; 22.2, 64.0, 47.1, 50.0, 44.4, 0.0, 50.0, 20.0, 33.3, 24.…</code></pre>
</div>
</div>
<p>Distribution of Goals by Player Position</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(players, <span class="fu">aes</span>(<span class="at">x =</span> Pos, <span class="at">y =</span> Goals)) <span class="sc">+</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">"lightblue"</span>) <span class="sc">+</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Distribution of Goals by Player Position"</span>,</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Position"</span>,</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Goals Scored"</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FUTBOLFINAL_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Histogram of Number of Players from Argentina Brazil and Italy</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>filtered_players <span class="ot">&lt;-</span> players <span class="sc">%&gt;%</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Nation <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"ARG"</span>, <span class="st">"BRA"</span>, <span class="st">"FRA"</span>))</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(filtered_players, <span class="fu">aes</span>(<span class="at">x =</span> Nation)) <span class="sc">+</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Number of Players: Argentina, Brazil, and Italy"</span>,</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Nation"</span>,</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Player Count"</span>) <span class="sc">+</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FUTBOLFINAL_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Relationship between Minutes played and Goals scored</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(players, <span class="fu">aes</span>(<span class="at">x =</span>Min, <span class="at">y =</span> Goals)) <span class="sc">+</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>, <span class="at">color =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Relationship Between Minutes Played and Goals Scored"</span>,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Minutes Played"</span>,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Goals Scored"</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FUTBOLFINAL_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>attackers <span class="ot">&lt;-</span> players <span class="sc">%&gt;%</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Pos <span class="sc">==</span> <span class="st">"FW"</span>)  </span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Correlation between minutes played and goals scored (for attackers)</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(attackers, <span class="fu">aes</span>(<span class="at">x =</span> Min, <span class="at">y =</span> Goals)) <span class="sc">+</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>, <span class="at">color =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Relationship Between Minutes Played and Goals Scored (Attackers)"</span>,</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Minutes Played"</span>,</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Goals Scored"</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FUTBOLFINAL_files/figure-html/unnamed-chunk-4-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtering only attackers who played at least 900 minutes</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>forwards <span class="ot">&lt;-</span> players <span class="sc">%&gt;%</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Pos <span class="sc">==</span> <span class="st">"FW"</span>, Min <span class="sc">&gt;=</span> <span class="dv">900</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(forwards, <span class="fu">aes</span>(<span class="at">x =</span> Min, <span class="at">y =</span> Goals)) <span class="sc">+</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>, <span class="at">color =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Relationship Between Minutes Played and Goals Scored (Attackers, Min 500 Mins)"</span>,</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Minutes Played"</span>,</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Goals Scored"</span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FUTBOLFINAL_files/figure-html/unnamed-chunk-4-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Running two sample T-test on brazilian players based on position</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>players <span class="sc">%&gt;%</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Nation <span class="sc">==</span> <span class="st">"BRA"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Pos) <span class="sc">%&gt;%</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_goals =</span> <span class="fu">mean</span>(Goals, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_goals =</span> <span class="fu">sd</span>(Goals, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">min_goals =</span> <span class="fu">min</span>(Goals, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">max_goals =</span> <span class="fu">max</span>(Goals, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 5
  Pos   mean_goals sd_goals min_goals max_goals
  &lt;chr&gt;      &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 DF         0.732    1.03          0         4
2 DFMF       0.2      0.447         0         1
3 FW         2.94     2.38          0         7
4 FWDF       2       NA             2         2
5 FWMF       3.25     3.01          0         7
6 GK         0        0             0         0
7 MF         0.895    1.05          0         3
8 MFDF       0        0             0         0
9 MFFW       2.12     4.05          0        12</code></pre>
</div>
</div>
<ol type="1">
<li>Do Brazilian players score more goals or italian players.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>brazil_italy <span class="ot">&lt;-</span> players <span class="sc">%&gt;%</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Nation <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"BRA"</span>, <span class="st">"ITA"</span>))</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Goals <span class="sc">~</span> Nation, <span class="at">data =</span> brazil_italy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  Goals by Nation
t = 2.2909, df = 161.98, p-value = 0.02326
alternative hypothesis: true difference in means between group BRA and group ITA is not equal to 0
95 percent confidence interval:
 0.07205142 0.97214645
sample estimates:
mean in group BRA mean in group ITA 
        1.3619048         0.8398058 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>players <span class="ot">&lt;-</span> players <span class="sc">%&gt;%</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Continent =</span> <span class="fu">case_when</span>(</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    Nation <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"BRA"</span>, <span class="st">"ARG"</span>, <span class="st">"URU"</span>, <span class="st">"COL"</span>, <span class="st">"CHI"</span>, <span class="st">"ECU"</span>, <span class="st">"PER"</span>, <span class="st">"PAR"</span>, <span class="st">"VEN"</span>, <span class="st">"BOL"</span>) <span class="sc">~</span> <span class="st">"South America"</span>,</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    Nation <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"ITA"</span>, <span class="st">"GER"</span>, <span class="st">"FRA"</span>, <span class="st">"ESP"</span>, <span class="st">"POR"</span>, <span class="st">"ENG"</span>, <span class="st">"BEL"</span>, <span class="st">"NED"</span>, <span class="st">"CRO"</span>, <span class="st">"SWE"</span>,</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"SUI"</span>, <span class="st">"DEN"</span>, <span class="st">"NOR"</span>, <span class="st">"POL"</span>, <span class="st">"AUT"</span>, <span class="st">"GRE"</span>, <span class="st">"SRB"</span>, <span class="st">"SCO"</span>, <span class="st">"UKR"</span>, <span class="st">"CZE"</span>) <span class="sc">~</span> <span class="st">"Europe"</span>,</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>    <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Other"</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  ))</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>south_europe <span class="ot">&lt;-</span> players <span class="sc">%&gt;%</span></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Continent <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"South America"</span>, <span class="st">"Europe"</span>))</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Goals <span class="sc">~</span> Continent, <span class="at">data =</span> south_europe)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  Goals by Continent
t = -1.9656, df = 332.37, p-value = 0.05017
alternative hypothesis: true difference in means between group Europe and group South America is not equal to 0
95 percent confidence interval:
 -0.5421695971  0.0002039032
sample estimates:
       mean in group Europe mean in group South America 
                  0.9951768                   1.2661597 </code></pre>
</div>
</div>
<p>Do more completed passes into 18 yard box result in more assists?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(players, <span class="fu">aes</span>(<span class="at">x =</span> PPA, <span class="at">y =</span> Assists)) <span class="sc">+</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>, <span class="at">color =</span> <span class="st">"darkgreen"</span>) <span class="sc">+</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"orange"</span>) <span class="sc">+</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Relationship Between Passes Into Box and Assists"</span>,</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Completed Passes Into 18-Yard Box"</span>,</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Assists"</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FUTBOLFINAL_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(players, <span class="fu">aes</span>(<span class="at">x =</span> PPA, <span class="at">y =</span> Assists)) <span class="sc">+</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>, <span class="at">color =</span> <span class="st">"darkgreen"</span>) <span class="sc">+</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"orange"</span>) <span class="sc">+</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Relationship Between Passes Into Box and Assists"</span>,</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Completed Passes Into 18-Yard Box"</span>,</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Assists"</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FUTBOLFINAL_files/figure-html/unnamed-chunk-7-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>players_filtered <span class="ot">&lt;-</span> players <span class="sc">%&gt;%</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(PPA <span class="sc">&gt;=</span> <span class="fl">1.2</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(players_filtered, <span class="fu">aes</span>(<span class="at">x =</span> PPA, <span class="at">y =</span> Assists)) <span class="sc">+</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>, <span class="at">color =</span> <span class="st">"purple"</span>) <span class="sc">+</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Completed Passes Into Box vs Assists (PPA ≥ 0.3)"</span>,</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Completed Passes Into 18-Yard Box (CrsPA)"</span>,</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Assists"</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FUTBOLFINAL_files/figure-html/unnamed-chunk-7-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Conclusion</p>
<p>I performed a two-sample t-test comparing the number of goals scored by Brazilian and Italian players. The p-value was 0.023, indicating a statistically significant difference. On average, Brazilian players scored more goals (1.36) than Italian players (0.84).However when I tried with European and South American players it was very similar and not statistically significant (p=1.05)</p>
<p>There is a relationship between more minutes played and goals scored. The more you play the more likely you are to score atleast for attackers.</p>
<p>I could not really draw a result from the PPA and assists.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>